@startuml
title AsteroidsFX - Component Diagram
skinparam linetype ortho
skinparam component {
    FontName Arial
    FontSize 16
    FontStyle Bold
}

'Asteroid'
[Asteroid] --(0-- [Common]
[Asteroid] --(0-- [CommonAsteroid]

'Bullet'
[Bullet] --(0-- [Common]
[Bullet] --(0-- [CommonBullet]

'Collision'
[Collision] --(0-- [Common]

'CommonAsteroid'
[CommonAsteroid] --(0-- [Common]

'CommonBullet'
[CommonBullet] --(0-- [Common]

'CommonDebris'
[CommonDebris] --(0-- [Common]

'CommonEnemy'
[CommonEnemy] --(0-- [Common]

'CommonEntityStylingService'
[CommonEntityStylingService] --(0-- [Common]

'CommonPlayer'
[CommonPlayer] --(0-- [Common]

'CommonScoreService'
[CommonScoreService] --(0-- [Common]

'CommonUIRenderingService'
[CommonUIRenderingService] --(0-- [Common]

'CommonWeapon'
[CommonWeapon] --(0-- [Common]

'Core'
[Core] --(0-- [Common]
[Core] --(0-- [CommonUIRenderingService]
[Core] --(0-- [CommonEntityStylingService]

'Debris'
[Debris] --(0-- [Common]
[Debris] --(0-- [CommonDebris]

'Enemy'
[Enemy] --(0-- [Common]
[Enemy] --(0-- [CommonEnemy]
[Enemy] --(0-- [CommonWeapon]

'EntityStylingService'
[EntityStylingService] --(0-- [Common]
[EntityStylingService] --(0-- [CommonEntityStylingService]

'Map'
[Map] --(0-- [Common]
[Map] --(0-- [CommonAsteroid]
[Map] --(0-- [CommonPlayer]
[Map] --(0-- [CommonEnemy]

'Player'
[Player] --(0-- [Common]
[Player] --(0-- [CommonWeapon]
[Player] --(0-- [CommonPlayer]


'ScoreService'
[ScoreService] --(0-- [Common]
[ScoreService] --(0-- [CommonScoreService]

'UIRenderingService'
[UIRenderingService] --(0-- [Common]
[UIRenderingService] --(0-- [CommonUIRenderingService]
[UIRenderingService] --(0-- [CommonScoreService]

'Weapon'
[Weapon] --(0-- [Common]
[Weapon] --(0-- [CommonWeapon]
[Weapon] --(0-- [CommonBullet]


@enduml