@startuml
title
<u>AsteroidsFX - Component Diagram</u>
end title

legend top
<font color=red >Note</font>
<i>Blue</i> components are those who are shared and meant to be used by any other component.
<i>Green</i> component is the core/main component.
end legend

skinparam linetype ortho
skinparam component {
    FontName Arial
    FontSize 16
    FontStyle Bold
}


together {
    component [Asteroid]
    component [Bullet]
    component [Debris]
    component [Collision]
    component [Enemy]
    component [Weapon]
    component [Map]
    component [ScoreService]
    component [Player]
    component [UIRenderingService]
    component [EntityStylingService]
}

together {
    component [CommonWeapon] #Lightblue
    component [Common] #Lightblue
    component [CommonAsteroid] #Lightblue
    component [CommonBullet] #Lightblue
    component [CommonEnemy] #Lightblue
    component [CommonScoreService] #Lightblue
    component [CommonPlayer] #Lightblue
}

component [Core] #Lightgreen

'Asteroid'
[Asteroid] -(0- [CommonAsteroid]

'Bullet'
[Bullet] -(0- [CommonBullet]

'Collision'
[Collision] -(0-- [Common]

'CommonAsteroid'
[CommonAsteroid] --(0-- [Common]

'CommonBullet'
[CommonBullet] --(0-- [Common]

'CommonEnemy'
[CommonEnemy] --(0-- [Common]


'CommonPlayer'
[CommonPlayer] --(0-- [Common]

'CommonScoreService'
[CommonScoreService] --(0-- [Common]

'CommonWeapon'
[CommonWeapon] --(0-- [Common]

'Core'
[Core] --(0-- [Common]

'Debris'
[Debris] -(0-- [Common]

'Enemy'
[Enemy] -(0- [CommonEnemy]
[Enemy] -(0- [CommonWeapon]


'Map'
[Map] -(0- [CommonAsteroid]
[Map] -(0- [CommonPlayer]
[Map] -(0- [CommonEnemy]

'Player'
[Player] -(0- [CommonWeapon]
[Player] -(0- [CommonPlayer]


'ScoreService'
[ScoreService] -(0- [CommonScoreService]

'UIRenderingService'
[UIRenderingService] -(0- [CommonScoreService]

'EntityStylingService'
[EntityStylingService] -(0- [Common]

'Weapon'
[Weapon] -(0- [CommonWeapon]
[Weapon] -(0- [CommonBullet]

@enduml