@startuml
title
<u>AsteroidsFX - Component Diagram</u>
end title

left to right direction

skinparam component {
    FontName Arial
    FontSize 16
    FontStyle Bold
}

component [\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCore\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n] as Core #Lightgreen

together {
    component [Asteroid] #Lightgreen
    component [Bullet] #Lightgreen
    component [Debris] #Lightgreen
    component [Collision] #Lightgreen
    component [Enemy] #Lightgreen
    component [Weapon] #Lightgreen
    component [Map] #Lightgreen
    component [ScoreService] #Lightgreen
    component [Player] #Lightgreen
    component [UIRenderingService] #Lightgreen
    component [EntityStylingService] #Lightgreen
}

together {
    component [CommonBullet] #Lightcoral
    component [CommonWeapon] #Lightcoral
    component [CommonAsteroid] #Lightcoral
    component [CommonScoreService] #Lightcoral
    component [CommonEnemy] #Lightcoral
    component [CommonPlayer] #Lightcoral
}

component [Common] #Khaki


Core ..> Common
CommonEnemy ...> Common
CommonScoreService ...> Common
CommonPlayer ...> Common
CommonBullet ...> Common
CommonWeapon ...> Common
CommonAsteroid ...> Common

Enemy ..> CommonEnemy
Enemy ...> CommonWeapon
Weapon ..> CommonWeapon
ScoreService ..> CommonScoreService
Player ..> CommonPlayer
Bullet ..> CommonBullet

Core ------(0- Enemy : IGamePluginService\nIEntityProcessingService\nIObserver
Core ---(0- Map : IGamePluginService\nIObserver
Core ---(0- Asteroid : IGamePluginService\nIEntityProcessingService\nIObserver
Core ---(0- Bullet : IGamePluginService\nIEntityProcessingService\nIObserver
Core ---(0- Player : IGamePluginService\nIEntityProcessingService\nIObserver
Core ---(0- Debris : IEntityProcessingService\nIObserver
Core ---(0- ScoreService : IObserver
Core ---(0- EntityStylingService : IEntityStylingService
Core ---(0- Collision : IPostEntityProcessingService
Core ---(0---- UIRenderingService : IUIRenderingService

Enemy -0)- Map : EnemySPI
Player -0)- Map : PlayerSPI
Asteroid -0)- Map : AsteroidSPI
Weapon -0)- Enemy : WeaponSPI
Weapon -0)- Player : WeaponSPI
Bullet -0)- Weapon : BulletSPI


@enduml